# Discord Hook

discord:

  enabled: false # Máº·c Ä‘á»‹nh 'false' sá»­ dá»¥ng thÃ¬ báº­t 'true'

  webhook-url: "https://discord.com/api/webhooks/xxxx"

  role-id: "123456789012345678" # role Ä‘á»ƒ tag khi cÃ³ káº¿t quáº£



# Thá»i gian 1 phiÃªn, tÃ­nh báº±ng giÃ¢y thá»±c táº¿

round-time: 60



# Giá»›i háº¡n sá»‘ tiá»n cÆ°á»£c má»™t phiÃªn

min-bet: 1000 # Tháº¥p nháº¥t

max-bet: 1000000 # Cao nháº¥t



jackpot-explode-chance: 0.3 # % hÅ© sáº½ ná»•

house-win-chance: 0.1 # 10% nhÃ  cÃ¡i sáº½ tháº¯ng (khÃ´ng ai nháº­n Ä‘Æ°á»£c tiá»n)



# Thay Ä‘á»•i loáº¡i tiá»n Ä‘á»ƒ giao dá»‹ch

currency:

  type: vault # vault | playerpoints | tokenmanager



# báº­t táº¯t hiá»‡u á»©ng quay hiá»ƒn thá»‹

display:

  titlebar: false # Máº·c Ä‘á»‹nh false

  actionbar: true



# BossBar

bossbar:

  title: "&6PhiÃªn #%round% &8| ğŸŸ¢ &bTÃ i &f(%tai% Ä‘) &8| &cğŸ”´ &cXá»‰u &f(%xiu% Ä‘) &8| &6ğŸ’° &dHÅ© &f(%jackpot% Ä‘) &8| &6â³&f %time%s"

  colors:

    green: 20

    yellow: 10



# Tá»· lá»‡ ná»• hÅ© top 3 ngÆ°á»i chÆ¡i nhiá»u nháº¥t

jackpot-share:

  top1: 60

  top2: 25

  top3: 15
