round-time: 60

currency:
  type: vault # vault | playerpoints | tokenmanager

bet:
  min: 1000
  max: 1000000

bossbar:
  title: "&6PhiÃªn #%round% &8| ğŸŸ¢ &bTÃ i &f(%tai% Ä‘) &8| ğŸ”´ &cXá»‰u &f(%xiu% Ä‘) &8| ğŸ’° &dHÅ© &f(%jackpot% Ä‘) &8| â³ &f%time%s"
  colors:
    green: 20
    yellow: 10

jackpot:
  start: 1000000
  tax: 0.05
  explode-chance: 0.03

discord:
  enable: true
  webhook-url: "WEBHOOK"
  channel-id: "123456789"
  role-id: "987654321"
